<?php

namespace Container76d1Jkb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_User_Provider_Concrete_BackendUsersService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'security.user.provider.concrete.backend_users' shared service.
     *
     * @return \Symfony\Component\Security\Core\User\InMemoryUserProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\security-core\\User\\UserProviderInterface.php';
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\security-core\\User\\InMemoryUserProvider.php';

        return $container->privates['security.user.provider.concrete.backend_users'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider(['admin' => ['password' => '$argon2id$v=19$m=65536,t=4,p=1$TmlGZFNPTXBtVi94Q20ydQ$nwKgstEg0IeDQwDFjaOZ4WCPENV0d294FW+8Xtz2Q2c', 'roles' => [0 => 'ROLE_ADMIN']]]);
    }
}
