<?php

namespace ContainerRGxFmG0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YhpFx2lService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yhpFx2l' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yhpFx2l'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'calculator' => ['privates', '.errored..service_locator.yhpFx2l.CartPriceCalculator', NULL, 'Cannot autowire service ".service_locator.yhpFx2l": it references class "CartPriceCalculator" but no such service exists.'],
            'session' => ['services', 'session', 'getSessionService', true],
        ], [
            'calculator' => 'CartPriceCalculator',
            'session' => '?',
        ]);
    }
}
