<?php

namespace ContainerRGxFmG0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored__ServiceLocator_YhpFx2l_CartPriceCalculatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.yhpFx2l.CartPriceCalculator' shared service.
     *
     * @return \CartPriceCalculator
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.yhpFx2l": it references class "CartPriceCalculator" but no such service exists.');
    }
}
