<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQTXor0I\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQTXor0I/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerQTXor0I.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerQTXor0I\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerQTXor0I\App_KernelTestDebugContainer([
    'container.build_hash' => 'QTXor0I',
    'container.build_id' => '159b76f3',
    'container.build_time' => 1593025331,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQTXor0I');
