<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'admin' => [[], ['_controller' => 'App\\Controller\\Admin\\DashboardController::index'], [], [['text', '/admin']], [], []],
    'product_all' => [[], ['_controller' => 'App\\Controller\\ApiController::index'], [], [['text', '/api/products']], [], []],
    'cart_index' => [['_locale'], ['_controller' => 'App\\Controller\\CartController::index'], [], [['text', '/cart/'], ['variable', '/', '[^/]++', '_locale', true]], [], []],
    'cart_add' => [['_locale', 'id'], ['_controller' => 'App\\Controller\\CartController::AddSale'], [], [['text', '/add'], ['variable', '/', '[^/]++', 'id', true], ['text', '/cart'], ['variable', '/', '[^/]++', '_locale', true]], [], []],
    'cart_show' => [['_locale'], ['_controller' => 'App\\Controller\\CartController::show'], [], [['text', '/cart/show'], ['variable', '/', '[^/]++', '_locale', true]], [], []],
    'cart_remove_product' => [['_locale', 'id'], ['_controller' => 'App\\Controller\\CartController::remove'], [], [['text', '/remove'], ['variable', '/', '[^/]++', 'id', true], ['text', '/cart'], ['variable', '/', '[^/]++', '_locale', true]], [], []],
    'cart_empty' => [['_locale'], ['_controller' => 'App\\Controller\\CartController::delete'], [], [['text', '/cart/empty'], ['variable', '/', '[^/]++', '_locale', true]], [], []],
    'csv' => [[], ['_controller' => 'App\\Controller\\CsvController::index'], [], [['text', '/csv']], [], []],
    'locale' => [['locale'], ['_controller' => 'App\\Controller\\DefaultController::locale'], [], [['variable', '/', '[^/]++', 'locale', true]], [], []],
    'product_index' => [['_locale'], ['_controller' => 'App\\Controller\\ProductController::index'], [], [['text', '/product/'], ['variable', '/', '[^/]++', '_locale', true]], [], []],
    'product_new' => [['_locale'], ['_controller' => 'App\\Controller\\ProductController::new'], [], [['text', '/product/new'], ['variable', '/', '[^/]++', '_locale', true]], [], []],
    'product_show' => [['_locale', 'slug'], ['_controller' => 'App\\Controller\\ProductController::show'], [], [['variable', '/', '[^/]++', 'slug', true], ['text', '/product'], ['variable', '/', '[^/]++', '_locale', true]], [], []],
    'product_edit' => [['_locale', 'id'], ['_controller' => 'App\\Controller\\ProductController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/product'], ['variable', '/', '[^/]++', '_locale', true]], [], []],
    'product_delete' => [['_locale', 'id'], ['_controller' => 'App\\Controller\\ProductController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/product'], ['variable', '/', '[^/]++', '_locale', true]], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\ProductController::index'], [], [['text', '/']], [], []],
];
