<?php

namespace ContainerQTXor0I;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExportCsvCommandService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Command\ExportCsvCommand' shared autowired service.
     *
     * @return \App\Command\ExportCsvCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\console\\Command\\Command.php';
        include_once \dirname(__DIR__, 4).'\\src\\Command\\ExportCsvCommand.php';

        $container->privates['App\\Command\\ExportCsvCommand'] = $instance = new \App\Command\ExportCsvCommand(NULL, ($container->services['router'] ?? $container->getRouterService()));

        $instance->setName('app:export:csv');

        return $instance;
    }
}
