<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container76d1Jkb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container76d1Jkb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container76d1Jkb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container76d1Jkb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container76d1Jkb\App_KernelDevDebugContainer([
    'container.build_hash' => '76d1Jkb',
    'container.build_id' => 'a850b7c1',
    'container.build_time' => 1593020055,
], __DIR__.\DIRECTORY_SEPARATOR.'Container76d1Jkb');
